### ISSUE TITLE
Crash when saved twice.

### ISSUE THREAD

**Issue by ghost** [Ekstazi/transactionbehavior#1]
Hi. There is a problem.
If I have to save twice same model instance with this behavior it will crash with exception:

Property "TransactionBehavior._transaction" is not defined. 

Sure. It will, because after first time commit this property not exist.

Salvation: use in commit method

$this->_transaction = null;

instead

unset($this->_transaction);

Have a good day.

**Comment by Ekstazi** [comment]
Fixed by commit ccd32cd

**Comment by ghost** [comment]
I'm afraid you not fixed it all. You fixed in rollback() function. Not in commit().

**Comment by Ekstazi** [comment]
Fixed by last commit
